name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Fetch S3 Bucket Name
        id: fetch_bucket_name
        run: |
          bucket_name=$(grep -oP 'bucket\s*=\s*"\K[^"]+' providers.tf)
          echo "::set-output name=bucket_name::$bucket_name"

      - name: Check if S3 bucket exists
        id: check_bucket
        run: |
          aws s3api head-bucket --bucket ${{ steps.fetch_bucket_name.outputs.bucket_name }}
        continue-on-error: true

      - name: Create S3 bucket if not exists
        if: steps.check_bucket.outcome != 'success'
        run: |
          aws s3api create-bucket --bucket ${{ steps.fetch_bucket_name.outputs.bucket_name }} --region <your-region> --create-bucket-configuration LocationConstraint=<your-region>

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan

      - name: Check Terraform status
        run: terraform state list
