name: Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for this deployment"
        type: choice
        options:
          - dev
          - prod
        required: true
      terraform_apply:
        description: "Whether to apply the Terraform changes"
        required: true
        default: "false"
      terraform_destroy:
        description: "Whether to destroy the Terraform infrastructure"
        required: true
        default: "false"

env:
  TF_STATE_BUCKET: ${{ github.event.inputs.environment }}-s3-state
  TF_VAR_env_name: ${{ github.event.inputs.environment }}
  TF_VAR_portal_prefix: ${{ github.event.inputs.environment }}

jobs:
  check_and_configure:
    name: Check S3 Bucket and Generate Backend Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check if S3 Bucket For State Exists
        id: check-bucket
        run: |
          if aws s3 ls "s3://$TF_STATE_BUCKET" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "S3 bucket does not exist"
            echo "Creating the bucket"
            # Create the bucket
            aws s3api create-bucket --bucket "$TF_STATE_BUCKET" --region $AWS_DEFAULT_REGION
            echo "S3 bucket created"
          else
            echo "S3 bucket exists"
          fi

      - name: Generate backend.conf
        run: |
          echo "bucket = \"$TF_STATE_BUCKET\"" > backend.conf
          echo "key    = \"$TF_VAR_env_name/terraform.tfstate\"" >> backend.conf
          echo "region = \"$AWS_DEFAULT_REGION\"" >> backend.conf
          echo "encrypt = true" >> backend.conf

  terraform_init_and_plan:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest
    needs: check_and_configure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform init
        run: |
          terraform init -backend-config=backend.conf

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform_init_and_plan
    if: ${{ github.event.inputs.terraform_apply == 'true' }}
    steps:
      - name: Terraform Apply
        run: |
          terraform apply tfplan

  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform_destroy == 'true' }}
    steps:
      - name: Terraform Init
        run: |
          terraform init
      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
